export type SiteProduct = {
  id: string;
  name: string;
  product: string;
  productUrl?: string;
  audience: string;
  problem: string;
  valueProposition: string;
  topic: string;
  monetization?: string;
  startupCost?: string;
  seoAngle?: string;
  seoThesis?: string;
  buyer?: string;
  economicDriver?: string;
  profitRationale?: string;
  primaryRisk?: string;
  searchQueries?: string[];
  probeArticleCount?: number;
  score?: number | null;
};
